### ISSUE TITLE
Cleanup of convertedDocument(s) after conversion successful

### ISSUE THREAD

**Issue by hajohn13** [groupdocs-total/GroupDocs.Total-for-Java-Spring#75]
After performing a convertedDocument.save() and a convertedDocument.dispose(), I am unable to clean up the temp file. Using the below code:

if (tmpFile != null)
{
          Files.deleteIfExists(Paths.get(destinationFile));
}

I received an error saying "The process cannot access the file because it is being used by another process."

Is there a better way to perform this cleanup?

John

**Comment by egorovpavel** [comment]
Hi @hajohn13, could you share the full source code of action you trying to perform.

**Comment by hajohn13** [comment]
That'll be difficult as I have made mods to the "GroupDocs.Total for Java
Spring" (before Groupdocs converted the conversion module to Angular) to be
integrated with our product.  I can send the ConversionServiceImpl.java,
but it won't be plug and play.

I guess my issue/bug is more related to the input streams and if they are
being closed properly after the file has been "converted" to a PDF.  I am
able to transfer the converted file and see that it is converted as it
should be, but simply can't clean it up once the conversion is done.

John

**Comment by koleslena** [comment]
Hi @hajohn13 , I can't understand what modifications you made, so could you provide your ConversionServiceImpl.java?

**Comment by hajohn13** [comment]
Closing issue
