### ISSUE TITLE
Blank Screen when rendering in IE 11

### ISSUE THREAD

**Issue by hajohn13** [groupdocs-total/GroupDocs.Total-for-Java-Spring#76]
I have uncommented and ran the npm updates in the angular viewer project listed in the polyfill.ts file and after running a ng build, and war build, I am still unable to view the project in IE 11.

Is there anything else that needs to be done to become IE 11 compatible?

John

**Comment by kegor** [comment]
Hi @hajohn13, we can't reproduce problem with blank screen in IE11 with just running the cloned repository code performing the steps described in readme file. But we can reproduce this problem after running the UI from https://github.com/groupdocs-total/GroupDocs.Total-Angular using the `ng serve` command, if you would like to use this approach could you please try to use the steps described in the official docs starting from https://angular.io/guide/deployment#local-development-in-older-browsers?
