### ISSUE TITLE
Modifying front end

### ISSUE THREAD

**Issue by hajohn13** [groupdocs-total/GroupDocs.Total-for-Java-Spring#86]
If I want to modify the front end angular components, is there any documentation on steps to take to do this ?

**Comment by bobkovalex** [comment]
Hi @hajohn13 

See if this [guide](https://gist.github.com/bobkovalex/0674e7d7c54a54daf01a37927df27b05) helps.

We are currently working on more detailed documentation on how-to.

Regards
